version: "3.9"

services:
  app:
    build: .
    ports:
      - "9090:9090"
    networks:
      - mynetwork
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_db
      MYSQL_USER: piyush
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
