version: "3.9"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: piyush
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: testdb
    ports:
      - 5433:5432
    networks:
      - mynetwork
    volumes:
      - postgres_volume:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

#docker volume is used to preserve the data
volumes:
  postgres_volume: